# automatically generated by the FlatBuffers compiler, do not modify

# namespace: devx

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Vehicle(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Vehicle()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVehicle(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Vehicle
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Vehicle
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Vehicle
    def Lat(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Vehicle
    def Long(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def VehicleStart(builder):
    builder.StartObject(3)

def Start(builder):
    VehicleStart(builder)

def VehicleAddId(builder, id):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder, id):
    VehicleAddId(builder, id)

def VehicleAddLat(builder, lat):
    builder.PrependFloat32Slot(1, lat, 0.0)

def AddLat(builder, lat):
    VehicleAddLat(builder, lat)

def VehicleAddLong(builder, long):
    builder.PrependFloat32Slot(2, long, 0.0)

def AddLong(builder, long):
    VehicleAddLong(builder, long)

def VehicleEnd(builder):
    return builder.EndObject()

def End(builder):
    return VehicleEnd(builder)
